# https://prettier.io/docs/en/configuration.html
printWidth: 160
tabWidth: 2
bracketSpacing: true
arrowParens: always
endOfLine: lf
singleQuote: true
trailingComma: all
semi: false
useTabs: false
htmlWhitespaceSensitivity: strict
